// auto-generated from Reparations-AO-Annotated+ comments
window.NOTES = window.NOTES || {};
function addNote(para, author, text, title="", source="") {
  if (!window.NOTES[para]) window.NOTES[para] = [];
  window.NOTES[para].push({ author, title, text, source });
}
addNote("para-32", "Shashwat Singh", "In addition to the Constituting Instrument that establishes an International Organization (IO), IOs also enter into need-based bilateral agreements with host states. The most common of these is a Headquarters Agreement (HQA), which grants privileges and immunities to the IO and its high-ranking officials. For instance, the United Nations has an HQA with the Government of the United States concerning its Headquarters in New York City, See https://treaties.un.org/doc/Publication/UNTS/Volume%2011/volume-11-I-147-English.pdf.", "", "");
addNote("para-33", "Shashwat Singh", "This is undoubtedly the most important paragraph of the Advisory Opinion (AO). Here, the Court proposed a compromise between the \u2018will theory\u2019 and the \u2018objective personality theory\u2019 to explain the independent legal personality of the United Nations as an international organization on the international plane. In essence, the Court stated that the international personality of an entity can be presumed when it performs acts that necessitate such a distinct legal personality.", "", "");
addNote("para-34", "Shashwat Singh", "Traditionally, states have been regarded as the primary actors in international law. The recognition of international organizations (IOs) as distinct actors capable of shaping international law gained prominence in the second half of the twentieth century with the proliferation of entities such as the European Union, the African Union, and the Organization of American States. Interestingly, in this paragraph, the Court referred to IOs as \u201csuper-states\u201d without clarifying the meaning of the term. The Court may have been suggesting that an IO, as an entity composed of multiple states, possesses rights and obligations on the international plane that are independent of those of its member states. In this context, it is worth examining the emergence and development of the European Union (EU), which is often described as a \u201csupranational organization,\u201d since states joining the EU delegate a portion of their sovereignty to it\u2014an essential feature enabling the EU to fulfill its unique mandate.  See https://opil.ouplaw.com/display/10.1093/law-oeeul/law-oeeul-e103, https://www.europarl.europa.eu/factsheets/en/sheet/8/supranational-decision-making-procedures", "", "");
addNote("para-35", "Shashwat Singh", "The Constituting Instrument or Agreement of any International Organization (IO) is crucial for understanding its broad mandate and, by extension, its rights and obligations under international law. The previously mentioned \u2018will theory\u2019 posits that IOs derive their international legal personality from the express or implied will of the entities that created them. The most straightforward way to discern this will is by examining the Constituting Instrument of the IO. See, https://documents.un.org/doc/undoc/gen/n23/034/04/pdf/n2303404.pdf.", "", "");
addNote("para-39", "Shashwat Singh", "The question of settling disputes of a municipal nature involving international organizations (IOs) remains a contentious issue. The UN International Law Commission is currently conducting a study on the topic of \u201cSettlement of Disputes Involving International Organizations,\u201d with August Reinisch serving as the Special Rapporteur. See, https://legal.un.org/ilc/guide/10_3.shtml.", "", "");
addNote("para-49", "Shashwat Singh", "The functional protection exercised by an organization over its agents is contrasted with a state\u2019s right to exercise diplomatic protection over its nationals. Although these two doctrines may overlap, the final decision to seek reparations is typically made through mutual cooperation between the international organization and the state to which the victim belongs.\nIn the present case, then UN Secretary-General Trygve Lie coordinated with Sweden to determine who would bring the claim against Israel, the respondent state, and to ensure that there was no duplication of reparations. This coordination ultimately led Sweden to waive any separate national claim.\nSee, https://www.un.org/unispal/document/auto-insert-178849/, https://www.jta.org/archive/israel-government-agrees-to-pay-damages-to-family-of-count-folke-bernadotte.", "", "");
addNote("para-53", "Shashwat Singh", "The reference here is to the principle of implied powers, also known as assumed powers, incidental powers, or inherent powers. See, https://opil.ouplaw.com/display/10.1093/law:epil/9780199231690/law-9780199231690-e467.", "", "");
addNote("para-54", "Shashwat Singh", "The most striking example of UN agents facing \u201cunusual dangers\u201d is that of UN peacekeepers, who have suffered numerous fatalities. The process of seeking reparations for their deaths is fairly complex and requires coordination among the United Nations, the troop-contributing country, and the country where the fatality occurred.\nSee, https://minusma.unmissions.org/en/security-council-press-statement-attack-against-united-nations-multidimensional-integrated, https://minusca.unmissions.org/en/minusca-peacekeeper-mauritania-killed-southern-region-central-african-republic. \nRecently, the topic \u201cAccountability for Crimes Against United Nations Peacekeepers\u201d has been added to the long-term programme of work of the UN International Law Commission (ILC).", "", "");
console.log("✅ notes loaded", Object.keys(window.NOTES));
;(function(){ window.NOTES_READY = true; window.dispatchEvent(new Event("notes:ready")); })();